#!/usr/bin/env python3
"""
Atomic Digital Product-Fit Advisor — GUI (v2, modern styling)
==========================================================
A desktop form for advisor.py, built with customtkinter for a clean, modern
card-based look instead of stock tkinter widgets.

INSTALL (on top of advisor.py's own deps):
    pip install customtkinter pillow

RUN:
    python gui.py

Keep gui.py, advisor.py, product_knowledge.json, and assets/atomic_digital_logo.png
all together in the same folder — this file imports advisor.py directly and
loads the logo from ./assets/.
"""

import re
import sys
import queue
import threading
from pathlib import Path
from tkinter import filedialog, messagebox

import customtkinter as ctk

import advisor  # the script we built earlier — must be in the same folder

try:
    from PIL import Image
    HAS_PIL = True
except ImportError:
    HAS_PIL = False


# ──────────────────────────────────────────────────────────────────────────
# Design tokens — light, clean, fintech-adjacent. Kept in one place so the
# whole look can be retuned without hunting through widget calls.
# ──────────────────────────────────────────────────────────────────────────
BG_MAIN     = "#F4F5F7"
BG_CARD     = "#FFFFFF"
BORDER      = "#E4E7EB"
TEXT_MAIN   = "#15181C"
TEXT_SUB    = "#70787F"
TEXT_FAINT  = "#A6ACB2"
ACCENT      = "#B8791F"
ACCENT_HOVER = "#9C6618"
GOOD        = "#1E8E5A"
BAD         = "#C0392B"
LOG_BG      = "#12161B"
LOG_TEXT    = "#D7DDE2"
LOG_FAINT   = "#5B646C"
LOG_ACCENT  = "#E8A33D"
LOG_GOOD    = "#5FD08A"
LOG_BAD     = "#F0796A"

STATUS_COLORS = {
    "ready":   ("#9AA1A8", "#EEF0F2", "Ready"),
    "running": (ACCENT,    "#FBF1DF", "Running"),
    "done":    (GOOD,      "#E7F6EE", "Done"),
    "error":   (BAD,       "#FBEAE7", "Error"),
}

FONT_FAMILY = "Helvetica Neue"
ASSETS_DIR = Path(__file__).resolve().parent / "assets"
LOGO_PATH = ASSETS_DIR / "atomic_digital_logo.png"

ctk.set_appearance_mode("light")


class QueueWriter:
    """Redirects advisor.py's print() calls into the GUI's log box."""
    def __init__(self, q):
        self.q = q

    def write(self, text):
        if text.strip():
            self.q.put(("log", text.rstrip("\n")))

    def flush(self):
        pass


DEFAULT_MODEL = None  # None -> advisor.py falls back to DEEPSEEK_MODEL env var, or "deepseek-v4-flash"


def card(parent, **kwargs):
    """A consistent rounded white card used throughout the layout."""
    defaults = dict(fg_color=BG_CARD, corner_radius=14, border_width=1, border_color=BORDER)
    defaults.update(kwargs)
    return ctk.CTkFrame(parent, **defaults)


def section_label(parent, text):
    return ctk.CTkLabel(
        parent, text=text.upper(),
        font=ctk.CTkFont(family=FONT_FAMILY, size=11, weight="bold"),
        text_color=TEXT_FAINT,
    )


# ── line classification for syntax highlighting ────────────────────────────
_DIVIDER_RE = re.compile(r'^[=\-─]{5,}$')
_HEADER_RE = re.compile(r'^[A-Z][A-Z0-9 ()/\-]{4,}$')
_SCORE_LINE_RE = re.compile(r'^\s*\[[█░]+\]\s*\d+/100')


def _classify_report_line(line: str) -> str | None:
    stripped = line.strip()
    if not stripped:
        return None
    if _DIVIDER_RE.match(stripped):
        return "divider"
    if stripped.startswith("RECOMMENDED:") or stripped.startswith("Score:"):
        return "recommended"
    if _SCORE_LINE_RE.match(stripped):
        return "score"
    if stripped.startswith("+ "):
        return "plus"
    if stripped.startswith("- "):
        return "minus"
    if stripped.startswith("? "):
        return "gap"
    if stripped.startswith("Generated by") or stripped.startswith("Pre-meeting prep"):
        return "faint"
    if _HEADER_RE.match(stripped) and len(stripped.split()) <= 8:
        return "h1"
    return None


def _classify_log_line(line: str) -> str | None:
    stripped = line.strip()
    if not stripped:
        return None
    if stripped.startswith("X FAILED") or "FAILED" in stripped:
        return "bad"
    if stripped.startswith("->") or stripped.startswith("Batch complete") or "Scraped" in stripped:
        return "good"
    if _DIVIDER_RE.match(stripped) or stripped.startswith("Processing:"):
        return "faint" if _DIVIDER_RE.match(stripped) else None
    if "Analyzing with" in stripped:
        return "accent"
    return None


class AdvisorGUI(ctk.CTk):
    def __init__(self):
        super().__init__()
        self.title("Atomic Digital — Product-Fit Advisor")
        self.geometry("880x820")
        self.minsize(760, 640)
        self.configure(fg_color=BG_MAIN)

        self.result_queue = queue.Queue()
        self.worker_thread = None
        self.last_report_text = ""
        self.last_analysis = None
        self.last_name = ""

        self._build_header()
        self._build_input_card()
        self._build_output()

        self.after(100, self._poll_queue)

    # ── header ──────────────────────────────────────────────────────────
    def _build_header(self):
        header = ctk.CTkFrame(self, fg_color="transparent")
        header.pack(fill="x", padx=28, pady=(24, 10))

        if HAS_PIL and LOGO_PATH.exists():
            try:
                img = Image.open(LOGO_PATH)
                ratio = img.width / img.height
                h = 42
                w = int(h * ratio)
                ctk_img = ctk.CTkImage(light_image=img, dark_image=img, size=(w, h))
                logo_label = ctk.CTkLabel(header, image=ctk_img, text="")
                logo_label.pack(side="left", padx=(0, 14))
            except Exception:
                pass

        title_box = ctk.CTkFrame(header, fg_color="transparent")
        title_box.pack(side="left", fill="y")
        ctk.CTkLabel(
            title_box, text="Product-Fit Advisor",
            font=ctk.CTkFont(family=FONT_FAMILY, size=22, weight="bold"),
            text_color=TEXT_MAIN,
        ).pack(anchor="w")
        ctk.CTkLabel(
            title_box, text="Pre-meeting research for prospective investors",
            font=ctk.CTkFont(family=FONT_FAMILY, size=12),
            text_color=TEXT_SUB,
        ).pack(anchor="w")

        status_box = ctk.CTkFrame(header, fg_color="transparent")
        status_box.pack(side="right", anchor="e")
        self.status_badge = ctk.CTkFrame(
            status_box, fg_color=STATUS_COLORS["ready"][1], corner_radius=999,
        )
        self.status_badge.pack(side="right")
        self.status_dot = ctk.CTkLabel(
            self.status_badge, text="●", font=ctk.CTkFont(size=11),
            text_color=STATUS_COLORS["ready"][0],
        )
        self.status_dot.pack(side="left", padx=(12, 5), pady=5)
        self.status_label = ctk.CTkLabel(
            self.status_badge, text=STATUS_COLORS["ready"][2],
            font=ctk.CTkFont(family=FONT_FAMILY, size=12, weight="bold"),
            text_color=TEXT_SUB,
        )
        self.status_label.pack(side="left", padx=(0, 14), pady=5)

        divider = ctk.CTkFrame(self, fg_color=BORDER, height=1, corner_radius=0)
        divider.pack(fill="x", padx=28, pady=(4, 0))

    def _set_status(self, state: str):
        color, bg, label = STATUS_COLORS[state]
        self.status_badge.configure(fg_color=bg)
        self.status_dot.configure(text_color=color)
        self.status_label.configure(text=label, text_color=color if state != "ready" else TEXT_SUB)

    # ── single-prospect input ────────────────────────────────────────────
    def _build_input_card(self):
        outer = card(self)
        outer.pack(fill="x", padx=28, pady=(0, 14))
        parent = ctk.CTkFrame(outer, fg_color="transparent")
        parent.pack(fill="x", padx=20, pady=16)
        parent.columnconfigure(1, weight=1)

        self.name_var = ctk.StringVar()

        self._labeled_entry(parent, 0, "Prospect name *", self.name_var, "e.g. Raffles Family Office")

        ctk.CTkLabel(
            parent, text="Website URL(s) *", font=ctk.CTkFont(family=FONT_FAMILY, size=13),
            text_color=TEXT_MAIN,
        ).grid(row=1, column=0, sticky="nw", padx=(4, 12), pady=(8, 8))
        self.website_box = ctk.CTkTextbox(
            parent, height=70, corner_radius=8, border_width=1, border_color=BORDER,
            fg_color=BG_MAIN, text_color=TEXT_MAIN,
            font=ctk.CTkFont(family="Menlo", size=12), wrap="word",
        )
        self.website_box.grid(row=1, column=1, sticky="ew", pady=8)

        ctk.CTkLabel(
            parent, text="One URL per line — e.g. the homepage plus a dedicated team/strategy page.",
            font=ctk.CTkFont(family=FONT_FAMILY, size=11), text_color=TEXT_FAINT,
        ).grid(row=2, column=1, sticky="w", pady=(0, 8))

        self.run_btn = ctk.CTkButton(
            parent, text="▶  Run Analysis", command=self._run_single,
            height=38, corner_radius=8, fg_color=ACCENT, hover_color=ACCENT_HOVER,
            font=ctk.CTkFont(family=FONT_FAMILY, size=13, weight="bold"),
        )
        self.run_btn.grid(row=3, column=1, sticky="e", pady=(8, 4))

    def _labeled_entry(self, parent, row, label, var, placeholder=""):
        ctk.CTkLabel(
            parent, text=label, font=ctk.CTkFont(family=FONT_FAMILY, size=13),
            text_color=TEXT_MAIN,
        ).grid(row=row, column=0, sticky="w", padx=(4, 12), pady=8)
        entry = ctk.CTkEntry(
            parent, textvariable=var, placeholder_text=placeholder,
            height=36, corner_radius=8, border_color=BORDER, fg_color=BG_MAIN,
        )
        entry.grid(row=row, column=1, sticky="ew", pady=8)
        return entry

    # ── output area (log + report) ──────────────────────────────────────
    def _build_output(self):
        outer = ctk.CTkFrame(self, fg_color="transparent")
        outer.pack(fill="both", expand=True, padx=28, pady=(0, 22))

        log_card = card(outer, height=130)
        log_card.pack(fill="x", pady=(0, 12))
        log_card.pack_propagate(False)
        section_label(log_card, "⚙  Progress").pack(anchor="w", padx=16, pady=(12, 4))
        self.log_box = ctk.CTkTextbox(
            log_card, fg_color=LOG_BG, text_color=LOG_TEXT,
            font=ctk.CTkFont(family="Menlo", size=12),
            corner_radius=10, wrap="word",
        )
        self.log_box.pack(fill="both", expand=True, padx=16, pady=(0, 14))
        self.log_box.tag_config("faint", foreground=LOG_FAINT)
        self.log_box.tag_config("good", foreground=LOG_GOOD)
        self.log_box.tag_config("bad", foreground=LOG_BAD)
        self.log_box.tag_config("accent", foreground=LOG_ACCENT)
        self.log_box.configure(state="disabled")

        report_card = card(outer)
        report_card.pack(fill="both", expand=True)
        header_row = ctk.CTkFrame(report_card, fg_color="transparent")
        header_row.pack(fill="x", padx=16, pady=(12, 4))
        section_label(header_row, "📄  Report").pack(side="left")
        ctk.CTkButton(
            header_row, text="⬇ PDF", command=self._save_report_pdf,
            height=28, width=80, corner_radius=7, fg_color=ACCENT,
            text_color="#1a1305", hover_color=ACCENT_HOVER,
            font=ctk.CTkFont(family=FONT_FAMILY, size=11, weight="bold"),
        ).pack(side="right", padx=(6, 0))
        ctk.CTkButton(
            header_row, text="⇩ Save to File...", command=self._save_report,
            height=28, width=124, corner_radius=7, fg_color=BG_MAIN,
            text_color=TEXT_MAIN, hover_color=BORDER, border_width=1, border_color=BORDER,
            font=ctk.CTkFont(family=FONT_FAMILY, size=11),
        ).pack(side="right")

        self.report_box = ctk.CTkTextbox(
            report_card, fg_color=BG_MAIN, text_color=TEXT_MAIN,
            font=ctk.CTkFont(family="Menlo", size=12),
            corner_radius=10, wrap="word",
        )
        self.report_box.pack(fill="both", expand=True, padx=16, pady=(0, 16))
        self.report_box.tag_config("h1", foreground=TEXT_MAIN)
        self.report_box.tag_config("divider", foreground=BORDER)
        self.report_box.tag_config("recommended", foreground=ACCENT)
        self.report_box.tag_config("score", foreground=ACCENT)
        self.report_box.tag_config("plus", foreground=GOOD)
        self.report_box.tag_config("minus", foreground=BAD)
        self.report_box.tag_config("gap", foreground=ACCENT_HOVER)
        self.report_box.tag_config("faint", foreground=TEXT_FAINT)
        self.report_box.tag_config("placeholder", foreground=TEXT_FAINT)
        # CTkTextbox.tag_config() forbids font= (incompatible with its DPI
        # scaling system) — reach the underlying tk.Text widget directly for
        # the two tags that need bold, a common workaround for this limit.
        self.report_box._textbox.tag_config("h1", font=("Menlo", 13, "bold"))
        self.report_box._textbox.tag_config("recommended", font=("Menlo", 13, "bold"))
        self.report_box.configure(state="disabled")
        self._show_report_placeholder()

        footer = ctk.CTkLabel(
            self, text="Atomic Digital Product-Fit Advisor  ·  Pre-meeting prep aid — not investment advice.",
            font=ctk.CTkFont(family=FONT_FAMILY, size=11), text_color=TEXT_FAINT,
        )
        footer.pack(pady=(0, 14))

    def _show_report_placeholder(self):
        self.report_box.configure(state="normal")
        self.report_box.delete("1.0", "end")
        self.report_box.insert(
            "1.0",
            "Your report will appear here once you run an analysis.\n\n"
            "Fill in a prospect name and website URL(s) above, then click Run Analysis.",
        )
        self.report_box.tag_add("placeholder", "1.0", "end")
        self.report_box.configure(state="disabled")

    # ── file dialogs ────────────────────────────────────────────────────
    @staticmethod
    def _default_save_dir() -> str:
        """
        A safe, always-writable default directory for save dialogs. Without
        this, tkinter falls back to the process's current working directory
        — which, depending on how the app was launched, can end up being
        "/" (the filesystem root, permanently read-only on macOS) rather
        than anywhere sensible.
        """
        downloads = Path.home() / "Downloads"
        return str(downloads) if downloads.is_dir() else str(Path.home())

    def _save_report(self):
        if not self.last_report_text.strip():
            messagebox.showinfo("Nothing to save", "Run an analysis first.")
            return
        default_name = advisor.re.sub(r'[^a-zA-Z0-9]', '_', self.last_name or "report") + ".txt"
        path = filedialog.asksaveasfilename(
            defaultextension=".txt", filetypes=[("Text file", "*.txt")],
            initialdir=self._default_save_dir(), initialfile=default_name,
        )
        if path:
            Path(path).write_text(self.last_report_text)
            messagebox.showinfo("Saved", f"Report saved to:\n{path}")

    def _save_report_pdf(self):
        if self.last_analysis is None:
            messagebox.showinfo("Nothing to save", "Run an analysis first.")
            return
        default_name = advisor.re.sub(r'[^a-zA-Z0-9]', '_', self.last_name or "report") + ".pdf"
        path = filedialog.asksaveasfilename(
            defaultextension=".pdf", filetypes=[("PDF file", "*.pdf")],
            initialdir=self._default_save_dir(), initialfile=default_name,
        )
        if not path:
            return
        try:
            advisor.generate_pdf_report(self.last_name, self.last_analysis, path)
            messagebox.showinfo("Saved", f"PDF report saved to:\n{path}")
        except RuntimeError as e:
            messagebox.showerror("Can't export PDF", str(e))
        except Exception as e:
            messagebox.showerror("PDF export failed", f"{e}")

    # ── validation ──────────────────────────────────────────────────────
    def _validate_and_prep(self):
        # No API-key check here — however you've configured DeepSeek access
        # in advisor.py (.env file or env vars), the actual OpenAI() client
        # call will raise a clear auth error if it's missing/invalid, and
        # that error surfaces via the try/except in the worker thread below.
        return DEFAULT_MODEL, advisor.HAS_SELENIUM

    # ── run actions ──────────────────────────────────────────────────────
    def _clear_boxes(self):
        for box in (self.log_box, self.report_box):
            box.configure(state="normal")
            box.delete("1.0", "end")
            box.configure(state="disabled")

    def _get_website_urls(self) -> list:
        """Read the multi-line website box, one URL per line, cleaned up."""
        raw = self.website_box.get("1.0", "end").strip()
        if not raw:
            return []
        return [line.strip() for line in raw.splitlines() if line.strip()]

    def _run_single(self):
        if self.worker_thread and self.worker_thread.is_alive():
            return
        name = self.name_var.get().strip()
        if not name:
            messagebox.showerror("Name required", "Enter a prospect name first.")
            return
        websites = self._get_website_urls()
        if not websites:
            messagebox.showerror(
                "Website required",
                "Enter at least one website URL to scrape (one per line).",
            )
            return
        prepped = self._validate_and_prep()
        if not prepped:
            return
        model_id, allow_selenium = prepped

        self._clear_boxes()
        self.last_analysis = None
        self.last_name = ""
        self.run_btn.configure(state="disabled")
        self._set_status("running")

        def work():
            old_stdout = sys.stdout
            sys.stdout = QueueWriter(self.result_queue)
            try:
                analysis = advisor.run_prospect(
                    name, websites, None, allow_selenium=allow_selenium, model=model_id
                )
                report = advisor.format_report(name, analysis)
                self.result_queue.put(("analysis", {"name": name, "analysis": analysis}))
                self.result_queue.put(("report", report))
            except Exception as e:
                self.result_queue.put(("error", str(e)))
            finally:
                sys.stdout = old_stdout
                self.result_queue.put(("done_single", None))

        self.worker_thread = threading.Thread(target=work, daemon=True)
        self.worker_thread.start()

    # ── polling ─────────────────────────────────────────────────────────
    def _insert_log_line(self, line: str):
        self.log_box.configure(state="normal")
        start = self.log_box.index("end-1c")
        self.log_box.insert("end", line + "\n")
        tag = _classify_log_line(line)
        if tag:
            self.log_box.tag_add(tag, start, f"{start} lineend")
        self.log_box.see("end")
        self.log_box.configure(state="disabled")

    def _set_report_text(self, text: str):
        self.report_box.configure(state="normal")
        self.report_box.delete("1.0", "end")
        for line in text.split("\n"):
            start = self.report_box.index("end-1c")
            self.report_box.insert("end", line + "\n")
            tag = _classify_report_line(line)
            if tag:
                self.report_box.tag_add(tag, start, f"{start} lineend")
        self.report_box.configure(state="disabled")

    def _poll_queue(self):
        try:
            while True:
                kind, payload = self.result_queue.get_nowait()
                if kind == "log":
                    self._insert_log_line(payload)
                elif kind == "analysis":
                    self.last_analysis = payload["analysis"]
                    self.last_name = payload["name"]
                elif kind == "report":
                    self.last_report_text = payload
                    self._set_report_text(payload)
                elif kind == "error":
                    self._set_status("error")
                    messagebox.showerror("Error", payload)
                elif kind == "done_single":
                    self.run_btn.configure(state="normal")
                    if self.status_label.cget("text") != "Error":
                        self._set_status("done")
        except queue.Empty:
            pass
        self.after(100, self._poll_queue)


if __name__ == "__main__":
    if not HAS_PIL:
        print("Note: pillow not installed — logo won't render. `pip install pillow`.")
    app = AdvisorGUI()
    app.mainloop()
